# Generated by Django 4.2.10 on 2024-02-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
